### PR TITLE
updated syntax error

### PR DESCRIPTION
**Pull request by wolfrayet0855**
correction to additional jokes add and syntax error

### CODE REVIEW

**Comment by UltiRequiem** [comment]
hey bro could you run `deno fmt` please

Also, nice project!

**Comment by wolfrayet0855** [comment]
thanks so much, my dad loves dad jokes.. haha. ran demo fit, good lookin out

**Comment by UltiRequiem** [comment]
lgtm, pull request linking your project in the readme when you finish, something like, "cool use cases", if you want ofc

**Comment by wolfrayet0855** [comment]
Thank you! Appreciate it!!

**Pull request merged**
